# 异常处理

## 抛出异常

throw 关键字

```c
void fun1(){
    ...
    throw 1;
    ...
    throw 0.1;
    ...
    throw string("ivalid index!");
}
```

## 捕获异常

try catch 表达式

```c
try{
    fun1(); // 当 fun1 执行 throw 1 时
}catch(int &e){
    // 处理 throw 1 异常, &e 的值为 1
}catch(double &e){
    // 处理 throw 0.1 异常, &e 的值为 0.1
}catch(string &aval){
    // 处理 throw string("ivalid index!"） 异常
}catch(...){
    // 处理其他不可预料的异常
}
```

## 异常类的定义

```c
class Exception{
public:
    virtual void printException();
    virtual ~Exception();
}

class IndexException : public Excepiton{
public:
    virtual void printException();
}
```

## 抛出异常类的对象

```c
void fun1(){
    ...
    throw Excepiton();
    ...
    throw IndexException();
}
```

## 捕获异常类的对象

```c
try{
    fun1(); // 当 fun1 执行 throw 1 时
}catch(Exception &e){
    e.printException(); // 这里可使用基类引用调用派生类的 printException() 函数
}
```